bin: clean up bash scripts
- Add help method
- Parse flags and arguments more robustly
- Remove unnecessary dependencies (e.g. bc)
- Combine small scripts into larger ones with subcommands

diff --git a/bin/brightness b/bin/brightness
--- a/bin/brightness
+++ b/bin/brightness
@@ -1,31 +1,67 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [inc PERCENT|dec PERCENT|set PERCENT|status]
+
+Increase, decrease, or set the screen brightness. If no subcommand is supplied,
+then status is run by default.
+
+    -h, --help     display this help and exit
+    inc PERCENT    increase the brightness by a percent
+    dec PERCENT    decrease the brightness by a percent
+    set PERCENT    set the brightness to a percent
+    status         print the current brightness"
+
+check_no_positionals() { [ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; } }
+
 brightness_file='/sys/class/backlight/intel_backlight/brightness'
 max_brightness_file='/sys/class/backlight/intel_backlight/max_brightness'
 curr_brightness=$(cat $brightness_file)
 min_brightness=1
 max_brightness=$(cat $max_brightness_file)
 
-[ -z "$1" ] && {
-  echo "$(echo "p = $curr_brightness / $max_brightness * 100; scale = 0; p / 1" | bc --mathlib)%"
+sub_status() {
+  check_no_positionals "$@"
+  echo "$((curr_brightness * 100 / max_brightness))%"
   exit 0
 }
 
-if [ "$1" = '-r' ]; then
-  [ -z "$2" ] && { echo 'Error: Argument 2 must be relative change in brightness.' && exit 1; }
-  curr_brightness=$((curr_brightness + $2))
-elif [ "$1" = '-a' ]; then
-  [ -z "$2" ] && { echo 'Error: Argument 2 must be absolute percentage in brightness.' && exit 1; }
-  curr_brightness="$(echo "p = $2 / 100.0 * $max_brightness; scale = 0; p / 1" | bc --mathlib)"
-else
-  echo 'Error: Argument 1 must be '-r' or '-a'.'
-  exit 1
-fi
+sub_set() {
+  [ -z "$1" ] && { echo "Error: subcommand set requires PERCENT." && exit 1; }
+  percent="$1"
+  shift
+  check_no_positionals "$@"
 
-if [ "$curr_brightness" -gt "$max_brightness" ]; then
-  curr_brightness=$max_brightness
-elif [ "$curr_brightness" -lt "$min_brightness" ]; then
-  curr_brightness=$min_brightness
-fi
+  curr_brightness=$((percent * max_brightness / 100))
+  if [ "$curr_brightness" -gt "$max_brightness" ]; then
+    curr_brightness=$max_brightness
+  elif [ "$curr_brightness" -lt "$min_brightness" ]; then
+    curr_brightness=$min_brightness
+  fi
+  echo "echo $curr_brightness > $brightness_file" | sudo bash
+}
 
-echo "echo $curr_brightness > $brightness_file" | sudo bash
+sub_inc() {
+  [ -z "$1" ] && { echo "Error: subcommand inc requires PERCENT." && exit 1; }
+  delta="$1"
+  shift
+  check_no_positionals "$@"
+
+  sub_set $((delta + curr_brightness * 100 / max_brightness + delta))
+}
+
+
+sub_dec() {
+  [ -z "$1" ] && { echo "Error: subcommand dec requires PERCENT." && exit 1; }
+  delta="$1"
+  shift
+  check_no_positionals "$@"
+
+  sub_set $((curr_brightness * 100 / max_brightness - delta))
+}
+
+sub="$1"
+[ "$sub" = '-h' ] || [ "$sub" = '--help' ] && { echo "$__help" && exit 0; }
+[ -z "$sub" ] && { sub_status "$@" && exit 0; }
+[ "$(command -v "sub_$sub")" ] || { printf "Error: unknown subcommand: %s.\\n\\n%s\\n" "$sub" "$__help" && exit 1; }
+shift
+"sub_$sub" "$@"
diff --git a/bin/bspwm-distribute-desktops b/bin/bspwm-distribute-desktops
--- a/bin/bspwm-distribute-desktops
+++ b/bin/bspwm-distribute-desktops
@@ -1,5 +1,39 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [-d|--desktops COUNT]
+
+Evenly distribute a specified number of bwpsm desktops across all active
+monitors. If there are more active desktops than specified, than trim the extra
+ones. If there are fewer active desktops than specified, than add new ones.
+
+    -h, --help              display this help and exit
+    -d, --desktops COUNT    the number of desktops to distribute
+                            (default: 10)"
+
+desktop_count=10
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -d | --desktops)
+      check_argument "$@"
+      desktop_count=$2
+      shift
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 monitors=$(
   xrandr |
     grep '\bconnected\b' |
@@ -12,11 +46,10 @@ monitors=$(polybar --list-monitors | cut --delimiter=':' --fields=1)
 monitor_count=$(echo "$monitors" | wc -l)
 focused_desktop=$(bspc query --desktops --desktop .focused)
 initial_desktop_count="$(bspc query --desktops | wc -l)"
-desktop_count=10
 q=$((desktop_count / monitor_count))
 r=$((desktop_count % monitor_count))
-
 total=0
+
 for curr_monitor in $monitors; do
   curr=$q
   if [ $r -gt 0 ]; then
@@ -24,7 +57,7 @@ for curr_monitor in $monitors; do
     r=$((r - 1))
   fi
 
-  if [ "$initial_desktop_count" -ge $desktop_count ]; then
+  if [ "$initial_desktop_count" -ge "$desktop_count" ]; then
     # Move desktops.
     for i in $(seq $total $((total + curr - 1))); do
       curr_desktop=$(bspc query --desktops --desktop "$i")
diff --git a/bin/display-album-art b/bin/display-album-art
--- a/bin/display-album-art
+++ b/bin/display-album-art
@@ -1,6 +1,39 @@
 #!/bin/sh
 
-music_dir=${XDG_MUSIC_DIR:-"$HOME/Music"}
+__help="Usage: ${0##*/} [-h|--help]
+
+Print the album cover of the current song being played by mpd. The cover art
+must be in the folder that the song file is located in.
+
+    -h, --help         display this help and exit
+    --music-dir DIR    mpd music directory
+                       (default: \$XDG_MUSIC_DIR)"
+
+unset music_dir
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    --music-dir)
+      check_argument "$@"
+      music_dir="$2"
+      shift
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+music_dir=${music_dir:-${XDG_MUSIC_DIR:-"$HOME/Music"}}
 
 update_background() {
   album="$(mpc --format %album% current)"
@@ -21,7 +54,15 @@ update_background() {
   fi
 }
 
+cleanly_exit() {
+  printf '\e]20;;100x100+1000+1000\a'
+  tput cnorm
+  stty echo
+  exit 0
+}
+
 trap 'update_background' USR1
+trap 'cleanly_exit' INT
 update_background
 clear
 tput civis
diff --git a/bin/dmenu-lpass b/bin/dmenu-lpass
--- a/bin/dmenu-lpass
+++ b/bin/dmenu-lpass
@@ -1,10 +1,45 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [-a|--account ACCOUNT]
+
+Display a dmenu for accounts stored in LastPass. The account is specified by
+the LPASS_EMAIL environment variable or the [-a|--account] flag in increasing
+order of priority.
+
+    -h, --help               display this help and exit
+    -a, --account ACCOUNT    the lpass account"
+
+unset lpass_email
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -a | --account)
+      check_argument "$@"
+      lpass_email=$2
+      shift
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+lpass_email=${lpass_email:-${LPASS_EMAIL}}
+
 dmenu_cmd() {
   rofi -i -fuzzy -dmenu -p "$1"
 }
 
-lpass status || lpass login "$LPASS_EMAIL"
+lpass status || lpass login "$lpass_email"
 selected_account=$(lpass ls --format '%aN' | dmenu_cmd 'lpass')
 [ -z "$selected_account" ] && exit
 lpass show --clip --password "$selected_account"
diff --git a/bin/dmenu-power b/bin/dmenu-power
--- a/bin/dmenu-power
+++ b/bin/dmenu-power
@@ -1,5 +1,26 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Display a dmenu for power options.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 dmenu_cmd() {
   rofi -i -fuzzy -dmenu -p "$1"
 }
diff --git a/bin/dmenu-xrandr b/bin/dmenu-xrandr
--- a/bin/dmenu-xrandr
+++ b/bin/dmenu-xrandr
@@ -1,5 +1,26 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Display a dmenu for monitor configuration using xrandr.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 xrandr_output="$(xrandr)"
 connected_monitors=$(echo "$xrandr_output" | grep '\bconnected\b' | cut --delimiter=' ' --fields=1)
 disconnected_monitors=$(echo "$xrandr_output" | grep '\bdisconnected\b' | cut --delimiter=' ' --fields=1)
@@ -23,12 +44,6 @@ resolution_options() {
   printf '%s\noff' "$available_resolutions"
 }
 
-post_init() {
-  init-polybar
-  init-background
-  bspwm-distribute-desktops
-}
-
 # Turn disconnected monitors off.
 for disconnected_monitor in $disconnected_monitors; do
   xrandr --output "$disconnected_monitor" --off
@@ -40,13 +55,13 @@ selected_monitor=$(printf '%s' "$connected_monitors" | dmenu_cmd 'output')
 selected_resolution=$(printf '%s' "$(resolution_options "$selected_monitor")" | dmenu_cmd 'mode')
 [ -z "$selected_resolution" ] && exit
 
-[ "$selected_resolution" = 'off' ] && { xrandr --output "$selected_monitor" --off && post_init && exit; }
+[ "$selected_resolution" = 'off' ] && { xrandr --output "$selected_monitor" --off && init-desktop && exit; }
 
 selected_rotation=$(printf '%b' "$rotation_options" | dmenu_cmd 'rotation')
 [ -z "$selected_rotation" ] && exit
 
 anchor_options=$(printf '%s' "$connected_monitors" | grep --invert-match "^$selected_monitor$")
-[ -z "$anchor_options" ] && { xrandr --output "$selected_monitor" --mode "$selected_resolution" --rotate "$selected_rotation" && post_init && exit; }
+[ -z "$anchor_options" ] && { xrandr --output "$selected_monitor" --mode "$selected_resolution" --rotate "$selected_rotation" && init-desktop && exit; }
 
 selected_anchor=$(printf '%s' "$anchor_options" | dmenu_cmd 'anchor')
 [ -z "$selected_anchor" ] && exit
@@ -55,4 +70,4 @@ selected_position=$(printf '%b' "$position_options" | dmenu_cmd 'position')
 [ -z "$selected_position" ] && exit
 
 xrandr --output "$selected_monitor" --mode "$selected_resolution" --"$selected_position" "$selected_anchor" --rotate "$selected_rotation"
-post_init
+init-desktop
diff --git a/bin/download-album-art b/bin/download-album-art
--- a/bin/download-album-art
+++ b/bin/download-album-art
@@ -1,14 +1,66 @@
 #!/bin/sh
 
-[ -z "$1" ] && { echo 'Error: Argument 1 must be an album name.' && exit 1; }
-album="$1"
-[ -z "$2" ] && { echo 'Error: Argument 2 must be an artist name.' && exit 1; }
-artist="$2"
-output_file="${3:-Cover.jpg}"
-api_endpoint='https://ws.audioscrobbler.com/2.0/?method=album.search'
+__help="Usage: ${0##*/} [-h|--help] [-o|--output FILE] [--artist ARTIST] [--album ALBUM]
 
-resp=$(curl --silent --get "$api_endpoint" --data-urlencode 'format=json' --data-urlencode "api_key=$LAST_FM_KEY" --data-urlencode "album=$album")
+Download an album cover using Last.fm's Audioscrobbler.
+
+    -h, --help           display this help and exit
+    -o, --output FILE    the name of the output file
+                         (default: Cover.jpg)
+    --artist ARTIST      the name of the album artist
+    --album ALBUM        the name of the album
+    --api-key API_KEY    Last.fm API key
+                         (default: \$LAST_FM_KEY)"
+
+unset output
+unset artist
+unset album
+unset api_key
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -o | --output)
+      check_argument "$@"
+      output=$2
+      shift
+      ;;
+    --artist)
+      check_argument "$@"
+      artist=$2
+      shift
+      ;;
+    --album)
+      check_argument "$@"
+      album=$2
+      shift
+      ;;
+    --api-key)
+      check_argument "$@"
+      api_key=$2
+      shift
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+[ -z "$artist" ] || [ -z "$album" ] && { echo "Error: must specify both ARTIST and ALBUM." && exit 1; }
+
+output="${output:-Cover.jpg}"
+api_endpoint='https://ws.audioscrobbler.com/2.0/?method=album.search'
+api_key=${api_key:-$LAST_FM_KEY}
+
+resp=$(curl --silent --get "$api_endpoint" --data-urlencode 'format=json' --data-urlencode "api_key=$api_key" --data-urlencode "album=$album")
 image_url=$(echo "$resp" | jq --raw-output ".results.albummatches.album[] | select(.artist == \"$artist\").image[-1][\"#text\"]")
 
-[ -z "$image_url" ] && { echo 'Error: Failed to find image.' && exit 1; }
-wget --quiet "$image_url" --output-document="$output_file"
+[ -z "$image_url" ] && { echo 'Error: failed to find image.' && exit 1; }
+wget --quiet "$image_url" --output-document="$output"
diff --git a/bin/get-cpu-temperature b/bin/get-cpu-temperature
--- a/bin/get-cpu-temperature
+++ b/bin/get-cpu-temperature
@@ -1,3 +1,24 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Prints the CPU temperature.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 echo $(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))°C
diff --git a/bin/get-frozen-pip-requirements b/bin/get-frozen-pip-requirements
--- a/bin/get-frozen-pip-requirements
+++ b/bin/get-frozen-pip-requirements
@@ -1,7 +1,37 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [-r|--requirements FILE]
+
+Prints the frozen pip requirements of a requirements file.
+
+    -h, --help                 display this help and exit
+    -r, --requirements FILE    the requirements file for pip"
+
+unset requirements_file
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -r | --requirements)
+      check_argument "$@"
+      requirements_file=$2
+      shift
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
 [ ! -x "$(command -v virtualenv)" ] && { echo 'Error: virtualenv is not installed.' && exit 1; }
-[ ! -f "$1" ] && { echo 'Error: Argument 1 must be requirements file.' && exit 1; }
+[ ! -f "$requirements_file" ] && { echo 'Error: FILE must be requirements file.' && exit 1; }
 
 tmp=$(mktemp --directory -t venv.XXXXXXXXXX) || exit 1
 trap 'rm -rf "$tmp"' EXIT
diff --git a/bin/get-weather b/bin/get-weather
--- a/bin/get-weather
+++ b/bin/get-weather
@@ -1,10 +1,43 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Display the temperature and weather conditions using OpenWeatherMap.
+
+    -h, --help           display this help and exit
+    --api-key API_KEY    OpenWeatherMap API key
+                         (default: \$OPEN_WEATHER_MAP_KEY)"
+
+unset api_key
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    --api-key)
+      check_argument "$@"
+      api_key=$2
+      shift
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 location=$(curl --silent ipinfo.io/loc)
 latitude=$(echo "$location" | cut --delimiter=',' --fields=1)
 longitude=$(echo "$location" | cut --delimiter=',' --fields=2)
 api_endpoint='http://api.openweathermap.org/data/2.5/weather'
-resp=$(curl --silent --get "$api_endpoint" --data-urlencode "lat=$latitude" --data-urlencode "lon=$longitude" --data-urlencode "APPID=$OPEN_WEATHER_MAP_KEY" --data-urlencode 'units=metric')
+api_key=${api_key:-${OPEN_WEATHER_MAP_KEY}}
+resp=$(curl --silent --get "$api_endpoint" --data-urlencode "lat=$latitude" --data-urlencode "lon=$longitude" --data-urlencode "APPID=$api_key" --data-urlencode 'units=metric')
 weather=$(echo "$resp" | jq --raw-output '.weather[0].main')
 temp=$(echo "$resp" | jq --raw-output '.main.temp')
 
diff --git a/bin/init-daemon b/bin/init-daemon
--- a/bin/init-daemon
+++ b/bin/init-daemon
@@ -1,16 +1,53 @@
 #!/bin/sh
 
-if [ "$1" = '-r' ]; then
-  restart=true
+__help="Usage: ${0##*/} [-h|--help] [-p|-process] [-s|--script] [-r|--restart]
+
+Start a daemon.
+
+    -h, --help               display this help and exit
+    -p, --process PROCESS    name of the daemon process
+    -s, --script SCRIPT      script to start the process
+                             (default: PROCESS)
+    -r, --restart            kill existing processes before starting"
+
+unset process
+unset script
+unset restart
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -p | --process)
+      check_argument "$@"
+      process=$2
+      shift
+      ;;
+    -s | --script)
+      check_argument "$@"
+      script=$2
+      shift
+      ;;
+    -r | --restart)
+      restart=1
+      ;;
+    *)
+      break;
+      ;;
+  esac
   shift
-fi
+done
 
-[ -z "$1" ] && { echo 'Error: Argument 1 must be a process name.' && exit 1; }
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+[ -z "$process" ] && { echo 'Error: must specific PROCESS.' && exit 1; }
 
-process=$1
-script=${2:-$1}
+script=${script:-$process}
 
-if [ $restart ]; then
+if [ ! -z $restart ]; then
   killall --quiet "$process"
   while pgrep --exact "$process" >/dev/null; do sleep 1; done
 fi
diff --git a/bin/init-monitors b/bin/init-monitors
--- a/bin/init-monitors
+++ b/bin/init-monitors
@@ -1,5 +1,26 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Initialize monitors.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 xrandr_output="$(xrandr)"
 connected_monitors=$(echo "$xrandr_output" | grep '\bconnected\b' | cut --delimiter=' ' --fields=1)
 disconnected_monitors=$(echo "$xrandr_output" | grep '\bdisconnected\b' | cut --delimiter=' ' --fields=1)
@@ -11,7 +32,7 @@ check_connected() {
 if check_connected 'DP-1'; then
   xrandr --output eDP-1 --mode 1600x900 --output DP-1 --auto --left-of eDP-1
 elif check_connected 'HDMI-1'; then
-  xrandr --output eDP-1 --mode 1600x900 --output HDMI-1 --auto --left-of eDP-1
+  xrandr --output eDP-1 --mode 1600x900 --output HDMI-1 --mode 1920x1080 --auto --left-of eDP-1
 else
   xrandr --output eDP-1 --mode 1920x1080
 fi
@@ -20,5 +41,4 @@ for disconnected_monitor in $disconnected_monitors; do
   xrandr --output "$disconnected_monitor" --off
 done
 
-init-polybar
-init-background
+init-desktop
diff --git a/bin/lock b/bin/lock
--- a/bin/lock
+++ b/bin/lock
@@ -1,5 +1,32 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [-s|--suspend]
+
+Lock the screen using i3lock.
+
+    -h, --help       display this help and exit
+    -s, --suspend    suspend after locking the screen"
+
+unset suspend
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -s | --suspend)
+      suspend=1
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 lock_file="${XDG_CONFIG_HOME:-"$HOME/.config"}/bspwm/images/lock.png"
 
 img_path() {
@@ -40,6 +67,9 @@ for dimensions in $sr; do
 done
 
 trap 'rm -f "$(img_path $index)"' EXIT
-i3lock -e -u -i "$(img_path $index)" && systemctl suspend
+i3lock -e -u -i "$(img_path $index)"
+if [ ! -z $suspend ]; then
+  systemctl suspend
+fi
 /bin/rm -f "$(img_path $index)"
 trap - EXIT
diff --git a/bin/notify-battery b/bin/notify-battery
--- a/bin/notify-battery
+++ b/bin/notify-battery
@@ -1,5 +1,26 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Send a notification via notify-send when the battery level is too low.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 battery='BAT0'
 
 while true; do
diff --git a/bin/record b/bin/record
--- a/bin/record
+++ b/bin/record
@@ -1,7 +1,47 @@
 #!/bin/sh
 
-videos_dir=${XDG_VIDEOS_DIR:-"$HOME/Videos"}
-file="$videos_dir/$(date +%s).mp4"
+__help="Usage: ${0##*/} [-h|--help] [-s|--select] [-v|--voice] [-o|--output FILE]
+
+Take a screencast.
+
+    -h, --help           display this help and exit
+    -o, --output FILE    the name of the output file
+    -s, --select         select an area of the screen to take a screencast of
+    -v, --voice          record "
+
+unset output
+unset select
+unset voice
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -s | --select)
+      select=1
+      ;;
+    -v | --voice)
+      voice=1
+      ;;
+    -o | --output)
+      check_argument "$@"
+      output=$2
+      shift
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+output=${output:-${XDG_VIDEOS_DIR:-"$HOME/Videos"}/$(date +%s).mp4}
 
 if pgrep --exact ffmpeg; then
   pkill --exact -INT ffmpeg
@@ -9,16 +49,17 @@ if pgrep --exact ffmpeg; then
   exit 0
 fi
 
-if [ "$1" = '-s' ]; then
+if [ -z $select ]; then
+  # Record entire desktop.
+  dimensions=$(xdpyinfo | awk '/dimensions/{print $2}')
+  offset="0,0"
+  notify-send --urgency=low 'Started video recording (desktop)'
+else
   # Record area.
   slop=$(slop --format '%wx%h %x,%y') || exit 1
   dimensions=$(echo "$slop" | cut --delimiter=' ' --fields=1)
   offset=$(echo "$slop" | cut --delimiter=' ' --fields=2)
   notify-send --urgency=low 'Started video recording (area)'
-  ffmpeg -f x11grab -s "$dimensions" -i :0.0+"$offset" -f alsa -i pulse "$file"
-else
-  # Record entire desktop.
-  dimensions=$(xdpyinfo | awk '/dimensions/{print $2}')
-  notify-send --urgency=low 'Started video recording (desktop)'
-  ffmpeg -f x11grab -s "$dimensions" -i :0.0 -f alsa -i pulse "$file"
 fi
+
+ffmpeg -f x11grab -s "$dimensions" -i :0.0+"$offset" -f pulse -i 2 "$output"
diff --git a/bin/robar-brightness b/bin/robar-brightness
--- a/bin/robar-brightness
+++ b/bin/robar-brightness
@@ -1,6 +1,26 @@
 #!/bin/sh
 
-curr_brightness=$(cat '/sys/class/backlight/intel_backlight/brightness')
-max_brightness=$(cat '/sys/class/backlight/intel_backlight/max_brightness')
+__help="Usage: ${0##*/} [-h|--help]
 
-robar show default "$(echo "$curr_brightness"/"$max_brightness" | bc --mathlib)"
+Display the current screen brightness using robar.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+brightness=$(brightness)
+value=$(echo "${brightness%\%}" | awk '{printf "%.2f\n", $1 / 100}')
+robar show default "$value"
diff --git a/bin/robar-brightness-server b/bin/robar-brightness-server
--- a/bin/robar-brightness-server
+++ b/bin/robar-brightness-server
@@ -1,5 +1,27 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Display the screen brightness using robar when the ACPI sysfs directory for
+screen brightness changes.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 inotifywait --quiet --monitor --event close_write /sys/class/backlight/intel_backlight/brightness | while read -r; do
   robar-brightness
 done
diff --git a/bin/robar-volume b/bin/robar-volume
--- a/bin/robar-volume
+++ b/bin/robar-volume
@@ -1,11 +1,31 @@
 #!/bin/sh
 
-amixer_info=$(amixer sget Master)
-left=$(echo "$amixer_info" | grep 'Left:' | awk --field-separator='[][]' '{ print $2 }')
-right=$(echo "$amixer_info" | grep 'Right:' | awk --field-separator='[][]' '{ print $2 }')
+__help="Usage: ${0##*/} [-h|--help]
 
-if echo "$amixer_info" | grep --fixed-strings --silent '[on]'; then
-  robar show default "$(echo "(${left%\%} + ${right%\%}) / 200" | bc --mathlib)"
+Display the current volume from amixer using robar.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+volume=$(volume)
+if echo "$volume" | grep --fixed-strings --silent 'muted'; then
+  value=$(echo "${volume%\%}" | awk '{printf "%.2f\n", $1 / 100}')
+  robar show mute "$value"
 else
-  robar show mute "$(echo "(${left%\%} + ${right%\%}) / 200" | bc --mathlib)"
+  value=$(echo "${volume%\% muted}" | awk '{printf "%.2f\n", $1 / 100}')
+  robar show default "$value"
 fi
diff --git a/bin/robar-volume-server b/bin/robar-volume-server
--- a/bin/robar-volume-server
+++ b/bin/robar-volume-server
@@ -1,5 +1,26 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Display the volume using robar when a change has been detected by pactl.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 pactl subscribe | while read -r line; do
   if echo "$line" | grep --extended-regexp --silent 'sink #0'; then
     robar-volume
diff --git a/bin/screenshot b/bin/screenshot
--- a/bin/screenshot
+++ b/bin/screenshot
@@ -1,17 +1,44 @@
 #!/bin/sh
 
-pictures_dir=${XDG_PICTURES_DIR:-"$HOME/Pictures"}
-file="$pictures_dir/Screenshots/$(date +%s).png"
+__help="Usage: ${0##*/} [-h|--help]
 
-if [ "$1" = '-s' ]; then
+Screenshot the entire desktop or an area of the desktop, and save the
+screenshot to the system clipboard.
+
+    -h, --help      display this help and exit
+    -s, --select    select an area to screenshot"
+
+unset select
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -s | --select)
+      select=1
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+file="${XDG_PICTURES_DIR:-"$HOME/Pictures"}/Screenshots/$(date +%s).png"
+
+if [ -z $select ]; then
+  # Screenshot entire desktop.
+  scrot "$file"
+  notify-send --urgency=low 'Took screenshot (desktop)'
+else
   # Screenshot area.
   slop=$(slop --format '%g') || exit 1
   import -window root -crop "$slop" "$file"
   notify-send --urgency=low 'Took screenshot (area)'
-else
-  # Screenshot entire desktop.
-  scrot "$file"
-  notify-send --urgency=low 'Took screenshot (desktop)'
 fi
 
 xclip "$file" -selection clipboard -target image/png
diff --git a/bin/set-timezone b/bin/set-timezone
--- a/bin/set-timezone
+++ b/bin/set-timezone
@@ -1,3 +1,24 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Set the timezone based on your public IP using WorldTimeAPI.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 sudo timedatectl set-timezone "$(curl -s worldtimeapi.org/api/ip.txt | sed -n 's/^timezone: //p')"
diff --git a/bin/tmux-prune b/bin/tmux-prune
--- a/bin/tmux-prune
+++ b/bin/tmux-prune
@@ -1,5 +1,26 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help]
+
+Kill all tmux sessions that are not currently attached.
+
+    -h, --help    display this help and exit"
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    *)
+      break;
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
 tmux list-sessions -F '#{session_name}:#{session_attached}' |
   awk --field-separator=':' '$2==0 {print $1}' |
   xargs -I '{}' tmux kill-session -t {}
diff --git a/bin/volume b/bin/volume
--- a/bin/volume
+++ b/bin/volume
@@ -1,31 +1,70 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [inc PERCENT|dec PERCENT|set PERCENT|status]
+
+Increase, decrease, toggle, or set the volume. If no subcommand is supplied,
+then status is run by default.
+
+    -h, --help     display this help and exit
+    inc PERCENT    increase the volume by a percent
+    dec PERCENT    decrease the volume by a percent
+    set PERCENT    set the volume to a percent
+    toggle         toggle the volume mute state
+    status         print the current brightness"
+
+check_no_positionals() { [ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; } }
+
 amixer_info=$(amixer sget Master)
 left=$(echo "$amixer_info" | grep 'Left:' | awk --field-separator='[][]' '{ print $2 }')
+left=${left%\%}
 right=$(echo "$amixer_info" | grep 'Right:' | awk --field-separator='[][]' '{ print $2 }')
+right=${right%\%}
 
-[ -z "$1" ] && {
-  if echo "$amixer_info" | grep --silent '[on]'; then
-    echo "$(echo "p = (${left%\%} + ${right%\%}) / 200 * 100; scale = 0; p / 1" | bc --mathlib)%"
+sub_status() {
+  check_no_positionals "$@"
+  volume=$(((left + right) * 100 / 200))
+  if echo "$amixer_info" | grep --silent '\[on\]'; then
+    echo "$volume%"
   else
-    echo 'muted'
+    echo "$volume% muted"
   fi
-  exit 0
 }
 
-if [ "$1" = '-r' ]; then
-  [ -z "$2" ] && { echo 'Error: Argument 2 must be relative change in volume.' && exit 1; }
-  if [ "$2" -lt 0 ]; then
-    amixer -D pulse set Master "${2#-}%-" 1>/dev/null
-  else
-    amixer -D pulse set Master "${2#+}%+" 1>/dev/null
-  fi
-elif [ "$1" = '-a' ]; then
-  [ -z "$2" ] && { echo 'Error: Argument 2 must be absolute percentage in volume.' && exit 1; }
-  amixer -D pulse set Master "$2%" 1>/dev/null
-elif [ "$1" = '-t' ]; then
+sub_inc() {
+  [ -z "$1" ] && { echo "Error: subcommand inc requires PERCENT." && exit 1; }
+  delta="$1"
+  shift
+  check_no_positionals "$@"
+
+  amixer -D pulse set Master "${delta#+}%+" 1>/dev/null
+}
+
+sub_dec() {
+  [ -z "$1" ] && { echo "Error: subcommand inc requires PERCENT." && exit 1; }
+  delta="$1"
+  shift
+  check_no_positionals "$@"
+
+  amixer -D pulse set Master "${delta#-}%-" 1>/dev/null
+}
+
+sub_set() {
+  [ -z "$1" ] && { echo "Error: subcommand set requires PERCENT." && exit 1; }
+  percent="$1"
+  shift
+  check_no_positionals "$@"
+
+  amixer -D pulse set Master "$percent%" 1>/dev/null
+}
+
+sub_toggle() {
+  check_no_positionals "$@"
   amixer -D pulse set Master 0+ toggle 1>/dev/null
-else
-  echo 'Error: Argument 1 must be '-r', '-a', or '-t'.'
-  exit 1
-fi
+}
+
+sub="$1"
+[ "$sub" = '-h' ] || [ "$sub" = '--help' ] && { echo "$__help" && exit 0; }
+[ -z "$sub" ] && { sub_status "$@" && exit 0; }
+[ "$(command -v "sub_$sub")" ] || { printf "Error: unknown subcommand: %s.\\n\\n%s\\n" "$sub" "$__help" && exit 1; }
+shift
+"sub_$sub" "$@"
diff --git a/bin/xrdb-compile-colors b/bin/xrdb-compile-colors
--- a/bin/xrdb-compile-colors
+++ b/bin/xrdb-compile-colors
@@ -1,16 +1,59 @@
 #!/bin/sh
 
-[ ! -f "$1" ] && { echo 'Error: Argument 1 must be template file.' && exit 1; }
-[ -z "$2" ] && { echo 'Error: Argument 2 must be the destination location.' && exit 1; }
+__help="Usage: ${0##*/} [-h|--help] [-t|--template FILE] [-d|--destination FILE] [-x|--xresources FILE]
 
-# Copy template to destination.
-cp -f "$1" "$2"
+Read the colors from Xresources to compile a template file. Each variable
+specified by {colorX} where X is an integer between 0 and 15, inclusive,
+will be replaced with the corresponding color in Xresources.
 
-# Load ~/.Xresources.
-xrdb "$HOME/.Xresources"
+    -h, --help                display this help and exit
+    -t, --template FILE       the template file to compile
+    -d, --destination FILE    the destination of the compiled file
+    -x, --xresources FILE     the Xresources file to read from
+                              (default: \$HOME/.Xresources)"
 
-# Query and substitute colors.
+unset template
+unset destination
+unset xresources
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -t | --template)
+      check_argument "$@"
+      template=$2
+      shift
+      ;;
+    -d | --destination)
+      check_argument "$@"
+      destination=$2
+      shift
+      ;;
+    -x | --xresources)
+      check_argument "$@"
+      xresources=$2
+      shift
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+[ ! -f "$template" ] && { echo 'TEMPLATE must be a file.' && exit 1; }
+
+xresources=${xresources:-${HOME}/.Xresources}
+
+cp -f "$template" "$destination"
+xrdb "$xresources"
 for i in $(seq 0 15); do
   color=$(xrdb -query -cpp g++ | awk '/.color'"$i":'/ { print $2; }')
-  sed --in-place "s/{color${i}}/${color}/g" "$2"
+  sed --in-place "s/{color${i}}/${color}/g" "$destination"
 done
diff --git a/bin/xrdb-export-colors b/bin/xrdb-export-colors
--- a/bin/xrdb-export-colors
+++ b/bin/xrdb-export-colors
@@ -1,11 +1,45 @@
 #!/bin/sh
 
+__help="Usage: ${0##*/} [-h|--help] [-x|--xresources FILE]
+
+Output commands to set COLOR_X environment variables where X is an integer
+between 0 and 15, inclusive, using the corresponding color in Xresources.
+
+    -h, --help                display this help and exit
+    -x, --xresources FILE     the Xresources file to read from
+                              (default: \$HOME/.Xresources)"
+
+unset xresources
+
+check_argument() { [ -z "$2" ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+
+while [ ! $# -eq 0 ]; do
+  case "$1" in
+    -h | --help)
+      echo "$__help"
+      exit 0
+      ;;
+    -x | --xresources)
+      check_argument "$@"
+      xresources=$2
+      shift
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
+
+[ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
+
+xresources=${xresources:-${HOME}/.Xresources}
+
 # Load ~/.Xresources.
 xrdb "$HOME/.Xresources"
 
 # Query and substitute colors.
 for i in $(seq 0 15); do
   color=$(xrdb -query -cpp g++ | awk '/.color'"$i":'/ { print $2; }')
-  export COLOR_"${i}"="${color}"
-  unset color
+  echo "export COLOR_$i=$color"
 done
