bin: change double quotes to single quotes and fix bspwm-distribute-desktops
bspwm-distribute-desktops correctly factors in mirrored displays.
Changed init-polybar to make it consistent with bspwm-distribute
desktops.

diff --git a/bin/brightness b/bin/brightness
--- a/bin/brightness
+++ b/bin/brightness
@@ -1,21 +1,21 @@
 #!/bin/sh
 
-brightness_file="/sys/class/backlight/intel_backlight/brightness"
-max_brightness_file="/sys/class/backlight/intel_backlight/max_brightness"
+brightness_file='/sys/class/backlight/intel_backlight/brightness'
+max_brightness_file='/sys/class/backlight/intel_backlight/max_brightness'
 curr_brightness=$(cat $brightness_file)
 min_brightness=1
 max_brightness=$(cat $max_brightness_file)
 
 [ -z "$1" ] && { echo "$(echo "p = $curr_brightness / $max_brightness * 100; scale = 0; p / 1" | bc --mathlib)%"; exit 0; }
 
-if [ "$1" = "-r" ]; then
-  [ -z "$2" ] && { echo "Error: Argument 2 must be relative change in brightness." && exit 1; }
+if [ "$1" = '-r' ]; then
+  [ -z "$2" ] && { echo 'Error: Argument 2 must be relative change in brightness.' && exit 1; }
   curr_brightness=$((curr_brightness + $2))
-elif [ "$1" = "-a" ]; then
-  [ -z "$2" ] && { echo "Error: Argument 2 must be absolute percentage in brightness." && exit 1; }
+elif [ "$1" = '-a' ]; then
+  [ -z "$2" ] && { echo 'Error: Argument 2 must be absolute percentage in brightness.' && exit 1; }
   curr_brightness="$(echo "p = $2 / 100.0 * $max_brightness; scale = 0; p / 1" | bc --mathlib)"
 else
-  echo "Error: Argument 1 must be '-r' or '-a'."
+  echo 'Error: Argument 1 must be '-r' or '-a'.'
   exit 1
 fi
 
diff --git a/bin/init-daemon b/bin/init-daemon
--- a/bin/init-daemon
+++ b/bin/init-daemon
@@ -1,11 +1,11 @@
 #!/bin/sh
 
-if [ "$1" = "-r" ]; then
+if [ "$1" = '-r' ]; then
   restart=true
   shift
 fi
 
-[ -z "$1" ] && { echo "Error: Argument 1 must be a process name." && exit 1; }
+[ -z "$1" ] && { echo 'Error: Argument 1 must be a process name.' && exit 1; }
 
 process=$1
 script=${2:-$1}
diff --git a/bin/magnet-to-torrent b/bin/magnet-to-torrent
--- a/bin/magnet-to-torrent
+++ b/bin/magnet-to-torrent
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
 
-[[ ! "$1" =~ xt=urn:btih:([^&/]+) ]] && { echo "Error: Argument 1 must be a valid magnet link." && exit 1; }
+[[ ! "$1" =~ xt=urn:btih:([^&/]+) ]] && { echo 'Error: Argument 1 must be a valid magnet link.' && exit 1; }
 download_dir=${XDG_DOWNLOAD_DIR:-"$HOME/Downloads"}
 echo "d10:magnet-uri${#1}:${1}e" > "$download_dir/meta-${BASH_REMATCH[1]}.torrent"
diff --git a/bin/volume b/bin/volume
--- a/bin/volume
+++ b/bin/volume
@@ -5,27 +5,27 @@ left=$(echo "$amixer_info" | grep 'Left:' | awk --field-separator='[][]' '{ prin
 right=$(echo "$amixer_info" | grep 'Right:' | awk --field-separator='[][]' '{ print $2 }')
 
 [ -z "$1" ] && {
-  if echo "$amixer_info" | grep --silent "\\[on\\]"; then
+  if echo "$amixer_info" | grep --silent '[on]'; then
     echo "$(echo "p = (${left%\%} + ${right%\%}) / 200 * 100; scale = 0; p / 1" | bc --mathlib)%"
   else
-    echo "muted"
+    echo 'muted'
   fi
   exit 0
 }
 
-if [ "$1" = "-r" ]; then
-  [ -z "$2" ] && { echo "Error: Argument 2 must be relative change in volume." && exit 1; }
+if [ "$1" = '-r' ]; then
+  [ -z "$2" ] && { echo 'Error: Argument 2 must be relative change in volume.' && exit 1; }
   if [ "$2" -lt 0 ]; then
     amixer -D pulse set Master "${2#-}%-" 1> /dev/null
   else
     amixer -D pulse set Master "${2#+}%+" 1> /dev/null
   fi
-elif [ "$1" = "-a" ]; then
-  [ -z "$2" ] && { echo "Error: Argument 2 must be absolute percentage in volume." && exit 1; }
+elif [ "$1" = '-a' ]; then
+  [ -z "$2" ] && { echo 'Error: Argument 2 must be absolute percentage in volume.' && exit 1; }
   amixer -D pulse set Master "$2%" 1> /dev/null
-elif [ "$1" = "-t" ]; then
+elif [ "$1" = '-t' ]; then
   amixer -D pulse set Master 0+ toggle 1> /dev/null
 else
-  echo "Error: Argument 1 must be '-r', '-a', or '-t'."
+  echo 'Error: Argument 1 must be '-r', '-a', or '-t'.'
   exit 1
 fi
