bin: fix scripts

diff --git a/bin/display-album-art b/bin/display-album-art
--- a/bin/display-album-art
+++ b/bin/display-album-art
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-set -euo pipefail
+set -uo pipefail
 
 __help="Usage: ${0##*/} [OPTIONS]
 
@@ -15,7 +15,7 @@ Options:
 
 unset music_dir
 
-check_argument() { [ $# -lt 2 ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+check_argument() { [ $# -ge 2 ] || { echo "Error: flag $1 requires an argument." && exit 1; } }
 
 while [ ! $# -eq 0 ]; do
   case "$1" in
@@ -43,13 +43,13 @@ update_background() {
   album="$(mpc --format %album% current)"
   file="$(mpc --format %file% current)"
   album_dir="${file%/*}"
-  [ -z "$album_dir" ] && exit 1
+  [ ! -z "$album_dir" ] || return
   album_dir="$music_dir/$album_dir"
 
-  covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\\(${album}\\|cover\\|folder\\|artwork\\|front\\).*[.]\\(jpe?g\\|png\\|gif\\|bmp\\)" \;)"
+  covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\\($album\\|cover\\|folder\\|artwork\\|front\\).*[.]\\(jpe?g\\|png\\|gif\\|bmp\\)" \;)"
   src="$(printf '%s' "$covers" | head --lines=1)"
 
-  if [ -n "$src" ]; then
+  if [ ! -z "$src" ]; then
     # Print cover art if it exists.
     printf '\e]20;%s;100x100+50+50:op=keep-aspect\a' "$src"
   else
diff --git a/bin/init-daemon b/bin/init-daemon
--- a/bin/init-daemon
+++ b/bin/init-daemon
@@ -17,7 +17,7 @@ unset process
 unset script
 unset restart
 
-check_argument() { [ $# -lt 2 ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+check_argument() { [ $# -ge 2 ] || { echo "Error: flag $1 requires an argument." && exit 1; } }
 
 while [ ! $# -eq 0 ]; do
   case "$1" in
@@ -46,11 +46,11 @@ while [ ! $# -eq 0 ]; do
 done
 
 [ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
-[ -z "$process" ] && { echo 'Error: must specific PROCESS.' && exit 1; }
+[ ! -z "${process:-}" ] || { echo 'Error: must specific PROCESS.' && exit 1; }
 
 script=${script:-$process}
 
-if [ ! -z $restart ]; then
+if [ ! -z ${restart:-} ]; then
   killall --quiet "$process"
   while pgrep --exact "$process" >/dev/null; do sleep 1; done
 fi
diff --git a/bin/record b/bin/record
--- a/bin/record
+++ b/bin/record
@@ -16,7 +16,7 @@ unset output
 unset select
 unset voice
 
-check_argument() { [ $# -lt 2 ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+check_argument() { [ $# -ge 2 ] || { echo "Error: flag $1 requires an argument." && exit 1; } }
 
 while [ ! $# -eq 0 ]; do
   case "$1" in
@@ -52,7 +52,7 @@ if pgrep --exact ffmpeg; then
   exit 0
 fi
 
-if [ -z $select ]; then
+if [ -z ${select:-} ]; then
   # Record entire desktop.
   dimensions=$(xdpyinfo | awk '/dimensions/{print $2}')
   offset="0,0"
@@ -65,7 +65,7 @@ else
   notify-send --urgency=low 'Started video recording (area)'
 fi
 
-if [ -z $voice ]; then
+if [ -z ${voice:-} ]; then
   input=1
 else
   input=2
diff --git a/bin/vim-pack b/bin/vim-pack
--- a/bin/vim-pack
+++ b/bin/vim-pack
@@ -19,7 +19,7 @@ Subcommands:
 check_no_positionals() { [ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; } }
 
 sub_add() {
-  [ -z "$1" ] && { echo "Error: subcommand set requires GIT_URL." && exit 1; }
+  [ $# -ge 1 ] || { echo "Error: subcommand set requires GIT_URL." && exit 1; }
   git_url="$1"
   shift
   check_no_positionals "$@"
@@ -28,7 +28,7 @@ sub_add() {
 }
 
 sub_remove() {
-  [ -z "$1" ] && { echo "Error: subcommand set requires GIT_URL." && exit 1; }
+  [ $# -ge 1 ] || { echo "Error: subcommand set requires GIT_URL." && exit 1; }
   package="$1"
   shift
   check_no_positionals "$@"
@@ -42,7 +42,7 @@ sub_remove() {
 }
 
 sub_update() {
-  [ -z "$1" ] && { echo "Error: subcommand set requires PACKAGE." && exit 1; }
+  [ $# -ge 1 ] || { echo "Error: subcommand set requires PACKAGE." && exit 1; }
   package="$1"
   shift
   check_no_positionals "$@"
@@ -56,16 +56,14 @@ sub_update_all() {
 }
 
 dir="$HOME/.vim/pack/plugins/start/"
-sub="$1"
-[ "$sub" = '-h' ] || [ "$sub" = '--help' ] && { echo "$__help" && exit 0; }
-if [ "$sub" = 'opt' ]; then
+if [ $# -ge 1 ] && [ "$1" = 'opt' ]; then
   shift
   dir="$HOME/.vim/pack/plugins/opt/"
-  sub="$1"
-else 
-  cd 
 fi
-[ -z "$sub" ] && { printf "Error: missing subcommand.\\n\\n%s\\n" "$__help" && exit 0; }
+
+[ $# -ge 1 ] || { printf "Error: missing subcommand.\\n\\n%s\\n" "$__help" && exit 0; }
+sub="$1"
+[ "$sub" = '-h' ] || [ "$sub" = '--help' ] && { echo "$__help" && exit 0; }
 [ "$(command -v "sub_$sub")" ] || { printf "Error: unknown subcommand: %s.\\n\\n%s\\n" "$sub" "$__help" && exit 1; }
 shift
 mkdir -p $dir
diff --git a/bin/xrdb-compile-colors b/bin/xrdb-compile-colors
--- a/bin/xrdb-compile-colors
+++ b/bin/xrdb-compile-colors
@@ -20,7 +20,7 @@ unset template
 unset destination
 unset xresources
 
-check_argument() { [ $# -lt 2 ] && { echo "Error: flag $1 requires an argument." && exit 1; } }
+check_argument() { [ $# -ge 2 ] || { echo "Error: flag $1 requires an argument." && exit 1; } }
 
 while [ ! $# -eq 0 ]; do
   case "$1" in
@@ -51,13 +51,13 @@ while [ ! $# -eq 0 ]; do
 done
 
 [ -z "$*" ] || { echo "Error: unexpected positional arguments: $*." && exit 1; }
-[ ! -f "$template" ] && { echo 'TEMPLATE must be a file.' && exit 1; }
+[ -f "$template" ] || { echo 'TEMPLATE must be a file.' && exit 1; }
 
-xresources=${xresources:-${HOME}/.Xresources}
+xresources=${xresources:-$HOME/.Xresources}
 
 cp -f "$template" "$destination"
 xrdb "$xresources"
 for i in $(seq 0 15); do
   color=$(xrdb -query -cpp g++ | awk '/.color'"$i":'/ { print $2; }')
-  sed --in-place "s/{color${i}}/${color}/g" "$destination"
+  sed --in-place "s/{color$i}/$color/g" "$destination"
 done
