Handle error cases in scripts, and add rofi scripts

diff --git a/bin/get-frozen-pip-requirements b/bin/get-frozen-pip-requirements
--- a/bin/get-frozen-pip-requirements
+++ b/bin/get-frozen-pip-requirements
@@ -1,9 +1,7 @@
 #!/bin/sh
 
-if ! [ -x "$(command -v virtualenv)" ]; then
-  echo "Error: virtualenv is not installed."
-  exit 1
-fi
+[ ! -x "$(command -v virtualenv)" ] && { echo "Error: virtualenv is not installed."; exit 1; }
+[ ! -f "$1" ] && { echo "Error: Argument 1 must be requirements file."; exit 1; }
 
 virtualenv --python=python3 tmp 1>/dev/null &&
   . ./tmp/bin/activate &&
diff --git a/bin/magnet-to-torrent b/bin/magnet-to-torrent
--- a/bin/magnet-to-torrent
+++ b/bin/magnet-to-torrent
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
 
-[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
-echo "d10:magnet-uri${#1}:${1}e" > ~/Downloads/meta-"${BASH_REMATCH[1]}".torrent
+[[ ! "$1" =~ xt=urn:btih:([^&/]+) ]] && { echo "Error: Argument 1 must be a valid magnet link."; exit 1; }
+DOWNLOAD_DIR=${XDG_DOWNLOAD_DIR:-"$HOME/Downloads"}
+echo "d10:magnet-uri${#1}:${1}e" > "$DOWNLOAD_DIR/meta-${BASH_REMATCH[1]}.torrent"
